name = "blah"
version = "0.8.2"

description = "fake data generation for gleam"
licences = ["Apache-2.0"]
links = [
  {title = "gleam", href = "https://gleam.run"},
]
repository = {type = "github", user = "massivefermion", repo = "blah"}

internal_modules = [
  "blah/en/*",
  "blah/utils",
  "blah/locales/*",
]

[dependencies]
birl = "~> 0.8"
gleam_stdlib = "~> 0.28"

[dev-dependencies]
gleeunit = "~> 0.10"
