name = "blah"
version = "0.11.0"

description = "fake data generation for gleam"
licences = ["Apache-2.0"]
links = [
  {title = "gleam", href = "https://gleam.run"},
]
repository = {type = "github", user = "massivefermion", repo = "blah"}

internal_modules = [
  "blah/en/*",
  "blah/utils",
  "blah/locales/*",
]

[dependencies]
birl = "~> 0.16"
gleam_stdlib = "~> 0.31"

[dev-dependencies]
gleeunit = "~> 0.11"
